return {
        'ellisonleao/gruvbox.nvim',
        'tpope/vim-surround',
        {"mason-org/mason.nvim", opts = {}},
        'nvim-lua/plenary.nvim',
        'nvim-telescope/telescope.nvim',
        'nvim-telescope/telescope-file-browser.nvim', 
        'folke/tokyonight.nvim',
        'nvim-treesitter/nvim-treesitter',
        'nvim-treesitter/nvim-tree-docs',
        'nvim-treesitter/nvim-treesitter-refactor',
        'nvim-treesitter/nvim-treesitter-context',
        'rktjmp/lush.nvim',
        'mbbill/undotree',
        'kartikp10/noctis.nvim',         
        'tpope/vim-dispatch',
        'ej-shafran/compile-mode.nvim',
        'iamcco/markdown-preview.nvim',
        'neovim/nvim-lspconfig',
        'ervandew/supertab',
}
